services:
  newspaparr:
    image: ghcr.io/egyptiangio/newspaparr:latest
    container_name: newspaparr
    ports:
      - "1851:1851"
      - "3333:3333"  # SOCKS5 proxy for CapSolver
    volumes:
      - ./data:/app/data
    restart: unless-stopped
    environment:
      # Basic Configuration
      - TZ=America/New_York
      - PUID=1000
      - PGID=1000
      
      # Anti-Detection Settings
      - RENEWAL_HEADLESS=false  # Use GUI mode with virtual display for better anti-detection
      - RENEWAL_SPEED=normal    # Delay speed: fast, normal, or slow
      - RENEWAL_RANDOM_UA=false  # Use static CapSolver-compatible User-Agent
      
      # CapSolver DataDome User Agent - MUST match across browser and CAPTCHA API
      - CAPSOLVER_USER_AGENT=Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/137.0.0.0 Safari/537.36
      
      # CAPTCHA Solving
      - CAPSOLVER_API_KEY=YOUR_CAPSOLVER_API_KEY_HERE  # CapSolver API key
      - PROXY_HOST=your-hostname.com  # Your dynamic DNS for CAPTCHA services to connect
      - SOCKS5_PROXY_PORT=3333  # SOCKS5 proxy port for CapSolver